#ifndef PCH_H
#define PCH_H
#include <locale.h>
#include <iostream>
#include <iomanip>
#include <set>
#include <list>
#include <fstream>
#include <stack>
#include <string>
using std::endl;
using std::list;
using std::set;
using std::string;
using std::cout;
using std::cin;
using std::setw;
using std::cerr;
using std::stack;
#endif 
